[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Kim Jae-Yong<alexj99@kookmin.ac.kr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
